### ISSUE TITLE
`linkcard` crashes

### ISSUE THREAD

**Issue by leshchenko1979** [vokimon/markdown-customblocks#7] opened 2022-02-24 04:40 UTC
I'm doing
```
::: linkcard https://www.youtube.com/c/ЗАЛЮБУЮНЕДВИЖКУ title="Разборы наших флиппинговых проектов"
```

I'm getting:
```
Traceback (most recent call last):
  File "C:\Users\leshc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\yamlns\__init__.py", line 39, in __getattr__
    return self[name]
KeyError: 'encoding'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2800.0_x64__qbz5n2kfra8p0\lib\threading.py", line 973, in _bootstrap_inner        
    self.run()
  File "C:\Users\leshc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\watchdog\observers\api.py", line 199, in run
    self.dispatch_events(self.event_queue, self.timeout)
  File "C:\Users\leshc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\watchdog\observers\api.py", line 372, in dispatch_events
    handler.dispatch(event)
  File "C:\Users\leshc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\watchdog\events.py", line 271, in dispatch
    self.on_any_event(event)
  File "C:\Users\leshc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\easywatch\easywatch.py", line 25, in wrapper
    return handler(event.event_type, event.src_path)
  File "C:\Users\leshc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\staticjinja\reloader.py", line 52, in event_handler
    self.site.render_template(t)
  File "C:\Users\leshc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\staticjinja\staticjinja.py", line 405, in render_template
    context = self.get_context(template)
  File "C:\Users\leshc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\staticjinja\staticjinja.py", line 313, in get_context
    new_context = _compute_context(context_like, template)
  File "C:\Users\leshc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\staticjinja\staticjinja.py", line 26, in _compute_context
    return context_like(template)
  File "C:\Users\leshc\flipio\markdown_site\build.py", line 103, in md_context
    "page_content_html": markdowner.convert(markdown_content),
  File "C:\Users\leshc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\markdown\core.py", line 264, in convert
    root = self.parser.parseDocument(self.lines).getroot()
  File "C:\Users\leshc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\markdown\blockparser.py", line 90, in parseDocument
    self.parseChunk(self.root, '\n'.join(lines))
  File "C:\Users\leshc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\markdown\blockparser.py", line 105, in parseChunk
    self.parseBlocks(parent, text.split('\n\n'))
  File "C:\Users\leshc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\markdown\blockparser.py", line 123, in parseBlocks
    if processor.run(parent, blocks) is not False:
  File "C:\Users\leshc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\customblocks\customblocks.py", line 223, in run
    result = generator(*outargs, **kwds)
  File "C:\Users\leshc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\customblocks\generators.py", line 47, in linkcard
    response = fetcher.get(url)
  File "C:\Users\leshc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\customblocks\utils\fetcher.py", line 66, in get
    return self._namespace2response(info)
  File "C:\Users\leshc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\customblocks\utils\fetcher.py", line 55, in _namespace2response
    result._content = namespace.text.encode(namespace.encoding)
  File "C:\Users\leshc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\yamlns\__init__.py", line 41, in __getattr__
    raise AttributeError(name)
AttributeError: encoding
```

**Comment by vokimon** [comment] 2022-03-02 13:44
Hi, Alexey,

I am unable to reproduce the bug. The example markdown just works for me. (No miniature image nor description metadata, thougth). It will help if you post the content of the cache in `fetchercache/linkcard/https_www.youtube.com_c_ЗАЛЮБУЮНЕДВИЖКУ`. Every time we store the cache with 'text' mode, the 'encoding' is supposed to be set. So maybe a previous error has corrupted its content. Copy it in order to post it here, try to remove the file and build it again. Keep a look on any error output.

**Comment by vokimon** [comment] 2023-04-17 16:57
One year open, I close the issue. Please, add any further info to reopen it.

**Closed by vokimon** 2023-04-17 16:57 UTC
Labels: bug, feedback required
